### ISSUE TITLE
erreur tooltip pages acheteurs et fournisseurs

### ISSUE THREAD

**Issue by barbitruc** [megalis-bretagne/focus-marches#1]
Bonjour,

Les tooltips des pages "acheteurs" et "fournisseurs" correspondent au focus Arnia 
![image](https://user-images.githubusercontent.com/118838346/203369799-39db2667-20f3-4e24-b221-eccdaeb4fceb.png)

**Comment by yguenneugues** [comment]
ok merci je corrige ça !

**Comment by ElodieTessier** [comment]
à remplacer SVP : 
quand je clique sur l'entrée Fournisseurs
![image](https://user-images.githubusercontent.com/97222408/212688306-437256fe-a669-4bf0-b187-8c84b4240459.png)

**Comment by ElodieTessier** [comment]
Je viens de vérifier, ça n'a pas été modifié par Mégalis :  
<img width="565" alt="2023-01-25 08_28_37-Marchés publics en Bourgogne-Franche-Comté" src="https://user-images.githubusercontent.com/97222408/214504991-903aaad7-c960-48d7-b930-37bb0f424137.png">
<img width="615" alt="2023-01-25 08_29_53-Les organismes du profil d'acheteur de Ternum BFC" src="https://user-images.githubusercontent.com/97222408/214504993-bc813c0b-9c39-4381-9d61-0005a57eef20.png">

**Comment by syji35** [comment]
Même issue que #2 .
Corriger en même temps.
