### ISSUE TITLE
PREPROD : tous les widgets renvoient vers la marque blanche de publicaiton des actes

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#10]
Bonjour,
Les 8 widgets de la page Acheteurs renvoient vers la marque blanche de publication des actes

**Comment by syji35** [comment]
En effet, correction déployé sur la prochaine release

**Comment by ElodieTessier** [comment]
test PRE-PROD : OK, je passe en **Prêt pour installation en PROD**
