### ISSUE TITLE
PREPROD - Accueil - manque le lien vers le site de Mégalis Bretagne

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#11]
Bonjour,
Le lien vers le site de Mégalis n'est plus fonctionnel :  
<img width="737" alt="2023-03-13 10_39_52-Données essentielles du profil d'acheteur de Mégalis Bretagne" src="https://user-images.githubusercontent.com/97222408/224664110-7bda6c9d-3362-4e44-87e9-c14230555bda.png">

**Comment by syji35** [comment]
@ElodieTessier 

Je comprends qu'il faut mettre un lien, vers megalis, sur le texte surligné en jaune. Est-ce bien cela ?

**Comment by ElodieTessier** [comment]
Bonjour @syji35 :
oui, c'est bien ça et voici le lien en question : https://geobretagne.fr/mviewer/?config=/apps/megalis-services/config.xml#

**Comment by ElodieTessier** [comment]
Est ce que le lien peut se faire sur l'ensemble des mots "adhérent au service proposé par Mégalis Bretagne" svp ?
