### ISSUE TITLE
PREPROD : le graphique "Distribution des achats par départements" ne s'affiche pas correctement

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#12]
Bonjour 
 le graphique "Distribution des achats par départements "
<img width="408" alt="2023-03-13 10_43_12-Données essentielles du profil d'acheteur de Mégalis Bretagne" src="https://user-images.githubusercontent.com/97222408/224664941-cd87caab-4c32-4b2c-b746-9086c6ff1203.png">
ne s'affiche pas correctement

**Comment by syji35** [comment]
Désormais, on va afficher les 5 meilleurs départements

**Comment by ElodieTessier** [comment]
test PRE-PROD : OK, je passe en **Prêt pour installation en PROD**
