### ISSUE TITLE
PREPROD - 2 boutons "comment lire ce graphique" non fonctionnels

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#13]
Bonjour,
Les  2 boutons "comment lire ce graphique"  de la **distribution temporelle des marchés et de la procédure suivie** de la page **Fournisseurs** ne sont  pas fonctionnels.

**Comment by syji35** [comment]
Corrigé.
Correction à installer en preprod

**Comment by ElodieTessier** [comment]
test PRE-PROD : OK, je passe en **Prêt pour installation en PROD**
