### ISSUE TITLE
PROD - retour arrière (dézoom) sur le graphique "Nature des contrats" KO

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#16]
Bonjour,
le retour arrière (dézoom) sur le graphique "Nature des contrats" KO
![image](https://github.com/megalis-bretagne/focus-marches/assets/97222408/bee79e34-be68-44e4-8abd-65b5804e5819)

**Comment by lvinsonneau** [comment]
@ElodieTessier : peux-tu recréer ce ticket sur le (nouveau) github [focus marchés](https://github.com/collec-data/focus-marches/issues) stp ?

**Comment by ElodieTessier** [comment]
OK, issue faite sur [focus marchés](https://github.com/collec-data/focus-marches/issues), je clos l'issue.
