### ISSUE TITLE
Echap pour fermer une fenêtre

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#3]
Est-il possible d'utiliser "Echap" pour fermer une fenêtre au lieu de cliquer sur le bouton fermer en bas à gauche ? exemple pour les liste fournisseurs. Merci

**Comment by lvinsonneau** [comment]
Pour moi, c'est à discuter en atelier UX, pas sûre que ce soit nécessaire et partagé.

**Comment by lvinsonneau** [comment]
en mode iframe, cela induirait un comportement non maîtrisé.
En suivi projet, on décide de ne pas faire.
