### ISSUE TITLE
Page recherche - "?" ne fonctionne pas

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#4]
Page recherche  "?" restent grisés
<img width="584" alt="2022-12-06 10_50_15-Recherche _ Marchés publics en Bourgogne-Franche-Comté" src="https://user-images.githubusercontent.com/97222408/205877915-da537ef6-1a1d-4301-83b0-fb39e672a2fc.png">

**Comment by syji35** [comment]
Il s'agit de tooltip derrière. Cela s'affiche bien au survol de la souris

**Comment by ElodieTessier** [comment]
_Pour info :_
KO sous Firefox sous version 91.9.0esr (64bits)
OK sous Edge version 112.0.1722.48 (Version officielle) (64 bits)
OK sous Chrome version 107.0.5304.107 (Build officiel) (64 bits)
