### ISSUE TITLE
Modification texte accueil

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#5]
Il s'agit de la dernière phrase :
Les contrats de type accords-cadres **multi-attributaires** sont exclus à ce jour, mais ils seront intégrés dans une prochaine version de l'outil.

**Comment by yguenneugues** [comment]
la phrase a été supprimée en preprod

**Comment by ElodieTessier** [comment]
Phrase non disponible en préprod

**Comment by ElodieTessier** [comment]
oui, exact, suite à l'atelier UX Design !

**Comment by syji35** [comment]
corrigé.
