### ISSUE TITLE
PROD : Manque l'année 2023 dans les graphiques

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#8]
Bonjour,
Il manque l'année 2023 aux graphiques.
<img width="449" alt="2023-03-13 10_16_45-Données essentielles du profil d'acheteur de Mégalis Bretagne" src="https://user-images.githubusercontent.com/97222408/224658222-6eb1df34-ae2e-4a24-88dd-6c7aa4f73759.png">

**Comment by syji35** [comment]
Correction déployé sur la prochaine release
