### ISSUE TITLE
PROD - Graphique "Contrats par département"

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/focus-marches#9]
Bonjour,
Est-il possible d'harmoniser les couleurs sur ce graphique svp ? pour éviter l couleur noire.
<img width="458" alt="2023-03-13 10_31_29-Données essentielles du profil d'acheteur de Mégalis Bretagne" src="https://user-images.githubusercontent.com/97222408/224661857-464facd9-b770-403a-979a-3b4c70c4af7f.png">

**Comment by syji35** [comment]
En effet, les codes couleurs étaient générés pour un maximum de 8 lignes. Pour une meilleure lisibilité du graphique (et une meilleure performance), nous passons désormais à une limite de 15 lignes maximum, avec un dégradé de couleurs associé.

**Comment by ElodieTessier** [comment]
test PRE-PROD : OK, je passe en **Prêt pour installation en PROD**
